apiVersion: v1
kind: Service
metadata:
  name: review-dashboard
  labels:
    app: review-dashboard
spec:
  selector:
    app: review-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP